apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: makeitjakes-lb-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: makeitjakes-backend-service
  annotations:
    run.googleapis.com/ingress: "all"
spec:
  type: ClusterIP
  selector:
    app: makeitjakes-backend
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: makeitjakes-frontend-service
  annotations:
    run.googleapis.com/ingress: "all"
spec:
  type: ClusterIP
  selector:
    app: makeitjakes-frontend
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: makeitjakes-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "makeitjakes-ip"
    networking.gke.io/v1beta1.FrontendConfig: "makeitjakes-lb-config"
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: makeitjakes-backend-service
            port:
              number: 80
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: makeitjakes-frontend-service
            port:
              number: 80 